"""The 32x32 capture boss. Symmetric (build right half, mirror). 4 frames: idle A/B (wing
flap), charge (eye bright+big), beam (eye blazing + glow). Renders a review sheet + writes
galaxigans_bossart.was. Palette slot 10: 1 outline, 2-6 purple body, 7-8 gold trim,
9-12 cyan emitter eye dim->white."""
import math, io
from PIL import Image, ImageDraw
W = H = 32
HEX = '0123456789ABCDEF'
CXL = 15.5   # mirror line between col 15 and 16

def tri(g, a, b, c, v):
    def sign(p, q, r): return (p[0]-r[0])*(q[1]-r[1]) - (q[0]-r[0])*(p[1]-r[1])
    minx=max(0,int(min(a[0],b[0],c[0]))); maxx=min(W-1,int(max(a[0],b[0],c[0])))
    miny=max(0,int(min(a[1],b[1],c[1]))); maxy=min(H-1,int(max(a[1],b[1],c[1])))
    for y in range(miny,maxy+1):
        for x in range(minx,maxx+1):
            p=(x+0.0,y+0.0); d1=sign(p,a,b); d2=sign(p,b,c); d3=sign(p,c,a)
            neg=(d1<0)or(d2<0)or(d3<0); pos=(d1>0)or(d2>0)or(d3>0)
            if not (neg and pos): g[y][x]=v

def build(frame):
    g = [[0]*W for _ in range(H)]
    flap = 1 if frame == 1 else 0
    spread = 1 if frame == 3 else 0
    # ---- right half (x >= 16), then mirror ----
    # body carapace: vertical egg, center on the mirror line
    for y in range(H):
        for x in range(16, W):
            dx = x - CXL; dy = y - 15.0
            if (dx/6.6)**2 + (dy/9.6)**2 <= 1.0:
                sh = dy*0.5 + dx*0.4
                g[y][x] = 5 if sh < -4 else 4 if sh < 0 else 3 if sh < 4 else 2
    # crown horns: two swept horns up-and-out
    tri(g, (17,9), (20,1), (22,5), 4)
    tri(g, (18,9), (22,5), (23,9), 3)
    # wings: big swept plates low on the sides (flap raises the tip)
    ty = 16 - flap*2 + spread*0      # tip y
    tx = 30 + spread
    tri(g, (20,12), (tx,ty), (21,25-spread), 3)        # wing body
    tri(g, (21,13), (tx,ty), (tx-2,ty+3), 6)           # leading sheen
    # gold trim along the leading edge
    for i in range(0, 11):
        fx = 20 + i; fy = 12 + (ty-12)*i/10.0
        if 16 <= int(fx) < W and 0 <= int(fy) < H: g[int(fy)][int(fx)] = 8
        if 0 <= int(fy)+1 < H: g[int(fy)+1][int(fx)] = 7
    # lower mandible claw
    tri(g, (17,22), (20,30), (22,24), 2)
    # mirror right -> left
    for y in range(H):
        for x in range(16):
            g[y][x] = g[y][31-x]
    # ---- centered features ----
    # antennae
    for k in range(3):
        g[max(0,5-k)][15-k-2] = 7; g[max(0,5-k)][16+k+1] = 7
    # the emitter eye (size + brightness by frame)
    er, dim, lit, hot = [(2.4,9,10,9),(2.4,9,10,9),(3.0,9,11,10),(3.6,10,12,11)][frame]
    ey = 15.5
    for y in range(H):
        for x in range(W):
            d = math.hypot(x-CXL, y-ey)
            if d < er-1.1: g[y][x] = hot+1 if frame==3 else lit+1
            elif d < er-0.3: g[y][x] = lit
            elif d < er: g[y][x] = dim
    if frame == 3:                        # beam-charge glow ring
        for y in range(H):
            for x in range(W):
                d = math.hypot(x-CXL, y-ey)
                if er <= d < er+1.2 and g[y][x] in (0,2,3): g[y][x] = 9
    # outline pass (silhouette edge)
    g2 = [r[:] for r in g]
    for y in range(H):
        for x in range(W):
            if g2[y][x]:
                if any(not(0<=y+dy<H and 0<=x+dx<W and g2[y+dy][x+dx]) for dy,dx in((-1,0),(1,0),(0,-1),(0,1))):
                    g[y][x] = 1
    return g

def torows(g): return [''.join(HEX[v] if v else '.' for v in r) for r in g]
PAL = [None,(32,8,40),(72,24,88),(104,48,120),(136,72,152),(176,108,192),(208,128,224),
       (200,160,48),(255,224,96),(32,96,160),(64,192,255),(176,236,255),(255,255,255)]
def colr(i): return PAL[i] if 0<i<len(PAL) else None

frames = [build(k) for k in range(4)]
labels = ['idle A','idle B','charge','beam']
S = 9
img = Image.new('RGB', (W*S*4+50, H*S+30), (12,12,22)); d = ImageDraw.Draw(img)
for k,g in enumerate(frames):
    ox = 10 + k*(W*S+8)
    for y,row in enumerate(torows(g)):
        for x,c in enumerate(row):
            cc = colr(int(c,16) if c in HEX else 0)
            if cc: d.rectangle([ox+x*S,20+y*S,ox+x*S+S-1,20+y*S+S-1], fill=cc)
    d.text((ox,6), labels[k], fill=(200,180,230))
img.save('projects/galaxigans/boss_sheet.png')

out = ["; galaxigans_bossart.was - the 32x32 capture boss, 4 frames (idle A/B, charge, beam).",
       "; Generated by tools/boss_design.py. Palette slot 10.", "",
       "module Galaxigans", ".balign 16", ".DATA", ".balign 16"]
for k,lbl in enumerate(['bossIdle0','bossIdle1','bossCharge','bossBeam']):
    rows = torows(frames[k])
    out.append('%-11s BYTE "%s"' % (lbl, rows[0]))
    for r in rows[1:]: out.append('%-11s BYTE "%s"' % ("", r))
    out.append("")
out.append("endmodule")
io.open('projects/galaxigans/galaxigans_bossart.was','w',encoding='ascii',newline='\n').write("\n".join(out)+"\n")
print("widths", set(len(r) for f in frames for r in torows(f)), "-> wrote bossart + sheet")
