"""Generate flap (2nd-frame) art for the original fleet species that lack one — butterfly /
boss / wasp. Reads their 16x16 art from galaxigans_data.inc, makes a flap by lifting the wing
columns one row, renders a review sheet, writes galaxigans_fleetanim.was."""
import re, io
from PIL import Image, ImageDraw
SRC = 'projects/galaxigans/galaxigans_data.inc'
HEX = '0123456789ABCDEF'

def load(path):
    sprites, cur = {}, None
    for line in io.open(path, encoding='utf-8', errors='replace'):
        m = re.match(r'^(\w+)\s+BYTE\s+"([0-9A-Fa-f.]*)"\s*$', line)
        m2 = re.match(r'^\s+BYTE\s+"([0-9A-Fa-f.]*)"\s*$', line)
        if m:
            cur = m.group(1); sprites[cur] = [m.group(2)]
        elif m2 and cur:
            sprites[cur].append(m2.group(1))
    return sprites

def val(c): return int(c, 16) if c in HEX else 0

def flap(rows):
    W = len(rows[0]); H = len(rows)
    g = [[val(c) for c in r.ljust(W, '.')] for r in rows]
    out = [[0]*W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            wing = abs(x - (W-1)/2.0) >= 4.5         # outer wing tips -> lift 1 row
            if wing:
                out[y][x] = g[y+1][x] if y+1 < H else 0
            else:
                out[y][x] = g[y][x]
    return [''.join(HEX[v] if v else '.' for v in r) for r in out]

sp = load(SRC)
SPECIES = [('butterflyArt', 'butterflyArt2'), ('bossArt', 'bossArt2'), ('waspArt', 'waspArt2')]
out_frames = {}
S = 12
img = Image.new('RGB', (16*S*6 + 70, 16*S + 30), (12, 12, 22)); d = ImageDraw.Draw(img)
def gray(i): return None if i == 0 else (min(255,40+i*16), min(255,46+i*16), min(255,58+i*16))
col = 0
for base, lbl2 in SPECIES:
    f1 = sp[base]; f2 = flap(f1); out_frames[lbl2] = f2
    for k, rows in enumerate([f1, f2]):
        ox = 10 + col*16*S
        for y, row in enumerate(rows):
            for x, c in enumerate(row):
                cc = gray(val(c))
                if cc: d.rectangle([ox+x*S, 18+y*S, ox+x*S+S-1, 18+y*S+S-1], fill=cc)
        d.text((ox, 4), base if k == 0 else 'flap', fill=(170,200,255))
        col += 1
img.save('projects/galaxigans/fleetanim_sheet.png')

doc = ["; galaxigans_fleetanim.was - flap (2nd) frames for butterfly/boss/wasp (the fleet species",
       "; that shipped single-frame). Generated by tools/fleet_anim.py (wing lift).", "",
       "module Galaxigans", ".balign 16", ".DATA", ".balign 16"]
for lbl2 in ('butterflyArt2', 'bossArt2', 'waspArt2'):
    rows = out_frames[lbl2]
    doc.append('%-12s BYTE "%s"' % (lbl2, rows[0]))
    for r in rows[1:]:
        doc.append('%-12s BYTE "%s"' % ("", r))
    doc.append("")
doc.append("endmodule")
io.open('projects/galaxigans/galaxigans_fleetanim.was', 'w', encoding='ascii', newline='\n').write("\n".join(doc) + "\n")
print("widths", set(len(r) for f in out_frames.values() for r in f), "-> wrote fleetanim + sheet")
