"""Spinning space-mine: a spiked metal sphere with a red trigger light, rotated into 8
frames (45 deg) so cycling them spins it. Renders a review sheet + writes galaxigans_mineart.was.
idx: 1 outline, 2-5 metal dark->sheen, 6 spike, 7-8 red light dim->bright."""
import math, io
from PIL import Image, ImageDraw
W = H = 16
CX = CY = 7.5
HEX = '0123456789ABCDEF'

def build_base():
    g = [[0] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            dx = x - CX; dy = y - CY; r = math.hypot(dx, dy); ang = math.atan2(dy, dx)
            # 8 spikes radiating, narrowing outward
            ka = round(ang / (math.pi / 4)) * (math.pi / 4)
            da = abs(((ang - ka + math.pi) % (2 * math.pi)) - math.pi)
            sw = 0.40 * (1.0 - (r - 3.0) / 5.2)
            if 3.0 <= r <= 7.3 and da < max(sw, 0.04):
                g[y][x] = 2 if r > 6.3 else 6
            # body sphere with a top-left sheen
            if r < 4.2:
                sh = dx * 0.55 + dy * 0.55
                if r > 3.5: g[y][x] = 1
                elif sh < -1.7: g[y][x] = 5
                elif sh < 0.2: g[y][x] = 4
                elif sh < 1.8: g[y][x] = 3
                else: g[y][x] = 2
    # red trigger light sitting on the top spike
    lx, ly = CX, CY - 5.0
    for y in range(H):
        for x in range(W):
            d = math.hypot(x - lx, y - ly)
            if d < 1.2: g[y][x] = 8
            elif d < 1.9 and g[y][x] in (6, 2, 0): g[y][x] = 7
    return g

def to_img(g):
    im = Image.new('L', (W, H), 0); px = im.load()
    for y in range(H):
        for x in range(W): px[x, y] = g[y][x]
    return im

def rot_rows(g, deg):
    im = to_img(g).rotate(deg, resample=Image.NEAREST, expand=False, fillcolor=0); px = im.load()
    return [''.join(HEX[px[x, y]] if px[x, y] else '.' for x in range(W)) for y in range(H)]

base = build_base()
frames = [rot_rows(base, -k * 45) for k in range(8)]   # 8 frames, clockwise

# review sheet
def colr(i):
    return [None,(24,24,32),(48,56,64),(80,88,104),(120,128,144),(176,184,200),
            (96,104,120),(128,32,24),(255,64,48)][i]
S = 16
img = Image.new('RGB', (W*S*8 + 16, H*S + 16), (12,12,22)); d = ImageDraw.Draw(img)
for k, rows in enumerate(frames):
    ox = 8 + k*W*S
    for y, row in enumerate(rows):
        for x, c in enumerate(row):
            cc = colr(int(c,16) if c in HEX else 0)
            if cc: d.rectangle([ox+x*S, 8+y*S, ox+x*S+S-1, 8+y*S+S-1], fill=cc)
img.save('projects/galaxigans/mine_sheet.png')

out = ["; galaxigans_mineart.was - spinning space-mine, 16x16, 8 rotation frames (45deg).",
       "; Generated by tools/mine_design.py. Palette slot 9.", "",
       "module Galaxigans", ".balign 16", ".DATA", ".balign 16"]
for k, rows in enumerate(frames):
    lbl = "mineArt%d" % k
    out.append('%-10s BYTE "%s"' % (lbl, rows[0]))
    for r in rows[1:]:
        out.append('%-10s BYTE "%s"' % ("", r))
    out.append("")
out.append("endmodule")
io.open('projects/galaxigans/galaxigans_mineart.was', 'w', encoding='ascii', newline='\n').write("\n".join(out) + "\n")
print("widths", set(len(r) for f in frames for r in f), "-> wrote mineart + sheet")
