"""Generate bank (rotated) frames for the new alien species + report palette index usage.
Reads the base 16x16 art from galaxigans_aliens2.was, rotates +/-22 deg (index-preserving
NEAREST), emits galaxigans_alienbanks2.was. Also prints which palette indices each uses."""
import re, io
from PIL import Image

SRC = 'projects/galaxigans/galaxigans_aliens2.was'
HEX = '0123456789ABCDEF'

def load(path):
    sprites, cur = {}, None
    for line in io.open(path, encoding='utf-8', errors='replace'):
        m = re.match(r'^(\w+)\s+BYTE\s+"([0-9A-Fa-f.]*)"\s*$', line)
        m2 = re.match(r'^\s+BYTE\s+"([0-9A-Fa-f.]*)"\s*$', line)
        if m:
            cur = m.group(1); sprites[cur] = [m.group(2)]
        elif m2 and cur:
            sprites[cur].append(m2.group(1))
    return sprites

def val(c): return int(c, 16) if c in HEX else 0

def to_img(rows):
    im = Image.new('L', (16, 16), 0)
    px = im.load()
    for y, r in enumerate(rows):
        for x, c in enumerate(r):
            if x < 16: px[x, y] = val(c)
    return im

def rot(rows, deg):
    im = to_img(rows).rotate(deg, resample=Image.NEAREST, expand=False, fillcolor=0)
    px = im.load()
    return [''.join(HEX[px[x, y]] if px[x, y] else '.' for x in range(16)) for y in range(16)]

sp = load(SRC)
# (type name, source label) — use frame 0 as the bank base
NEW = [('Jelly', 'jellyfishArt'), ('Beetle', 'beetleArt'), ('Sting', 'stingrayArt')]

out = ["; galaxigans_alienbanks2.was - bank (rotated) frames for the NEW species used in later",
       "; waves (jellyfish / beetle / stingray). Generated by tools/newspecies.py (+/-22 deg).", "",
       "module Galaxigans", ".balign 16", ".DATA", ".balign 16"]
for nm, lbl in NEW:
    rows = sp[lbl]
    used = sorted(set(val(c) for r in rows for c in r if c in HEX))
    print('%-10s uses indices %s' % (lbl, used))
    for side, deg in [('L', 22), ('R', -22)]:
        rr = rot(rows, deg)
        artlbl = 'f%sBank%sArt' % (nm, side)
        out.append('%-14s BYTE "%s"' % (artlbl, rr[0]))
        for r in rr[1:]:
            out.append('%-14s BYTE "%s"' % ("", r))
        out.append("")
out.append("endmodule")
io.open('projects/galaxigans/galaxigans_alienbanks2.was', 'w', encoding='ascii', newline='\n').write("\n".join(out) + "\n")
print("wrote galaxigans_alienbanks2.was")
