"""A little white-spacesuit pilot (a life token) — 12x16, single frame. Renders a review
sheet + writes galaxigans_pilotart.was. Palette slot 11: 1 outline, 2-4 suit shadow/white/hi,
6 visor cyan, 7 chest light."""
import io
from PIL import Image, ImageDraw
W, H = 12, 16
HEX = '0123456789ABCDEF'

def build():
    g = [[0]*W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            dx = x - 5.5
            if 1 <= y <= 5 and (dx/4.0)**2 + ((y-3)/3.0)**2 <= 1.0:   # helmet
                g[y][x] = 3
            if 2 <= y <= 4 and (dx/3.0)**2 + ((y-3.2)/1.7)**2 <= 1.0: # visor
                g[y][x] = 6
            if 6 <= y <= 12 and 2 <= x <= 9:                          # torso
                g[y][x] = 3
            if 7 <= y <= 10 and (x <= 2 or x >= 9):                   # arms
                g[y][x] = 3
            if 13 <= y <= 15 and (3 <= x <= 4 or 7 <= x <= 8):        # legs
                g[y][x] = 3
    for y in range(6, 13):                                            # right-side shadow
        for x in range(W):
            if g[y][x] == 3 and dx2(x) > 1.4:
                g[y][x] = 2
    g[8][5] = 7; g[8][6] = 7                                          # chest light
    if g[2][4]: g[2][4] = 4                                           # helmet glint
    g2 = [r[:] for r in g]
    for y in range(H):
        for x in range(W):
            if g2[y][x] and any(not (0 <= y+dy < H and 0 <= x+dx < W and g2[y+dy][x+dx])
                                for dy, dx in ((-1,0),(1,0),(0,-1),(0,1))):
                g[y][x] = 1
    return g

def dx2(x): return x - 5.5

g = build()
rows = [''.join(HEX[v] if v else '.' for v in r) for r in g]
PAL = [None,(32,40,48),(160,168,184),(232,236,244),(255,255,255),(0,0,0),(64,192,255),(255,128,32)]
S = 16
img = Image.new('RGB', (W*S+16, H*S+16), (12,12,22)); d = ImageDraw.Draw(img)
for y, row in enumerate(rows):
    for x, c in enumerate(row):
        cc = PAL[int(c,16)] if c in HEX and int(c,16) < len(PAL) else None
        if cc: d.rectangle([8+x*S, 8+y*S, 8+x*S+S-1, 8+y*S+S-1], fill=cc)
img.save('projects/galaxigans/pilot_sheet.png')

out = ["; galaxigans_pilotart.was - a white-spacesuit pilot (life token), 12x16. Palette slot 11.",
       "; Generated by tools/pilot_design.py.", "",
       "module Galaxigans", ".balign 16", ".DATA", ".balign 16",
       'pilotArt   BYTE "%s"' % rows[0]]
for r in rows[1:]:
    out.append('%-10s BYTE "%s"' % ("", r))
out.append("endmodule")
io.open('projects/galaxigans/galaxigans_pilotart.was', 'w', encoding='ascii', newline='\n').write("\n".join(out) + "\n")
print("widths", set(len(r) for r in rows), "rows", len(rows), "-> wrote pilotart + sheet")
